### PR TITLE
Allow users to override aspects of the Makefile.

### PR DESCRIPTION
**Pull request by ltratt**
We need to override these in order for ykclua to be able to test things.

### CODE REVIEW

**Comment by vext01** [comment]
Could this repo have been a fork? Not in git perhaps?

**Comment by vext01** [comment]
Do we need to add this to CI?

**Comment by ltratt** [comment]
1. No because the version the Lua folk have on github is very out of date (by some years IIRC).
2. Given that we need to patch things, having it in git seems sensible.

I hope that we rarely if ever do anything meaningful to this repo, so I'm not sure it's worth adding it to CI.

**Comment by vext01** [comment]
> Given that we need to patch things, having it in git seems sensible.

I meant, is upstream not in git, but you answered the question with 1.

OK, let's go.

**Pull request merged**
